### ISSUE TITLE
Error: Sample Bernoulli graphs with `dcsbm`

### ISSUE THREAD

**Issue by fchen365** [RoheLab/fastRG#18]
The following Bernoulli graph is not too dense. But the function refuses to return a sample. 

Code: 

```{r}
K = 10 ## true graph dimension
N = 2000 ## number of nodes
theta <- rexp(N, rate = 5) ## exp dist
pi <- 1.1 ^ seq(10) ## block size 
B <- matrix(.2, K, K); diag(B) <- .7  ## block connectivity matrix

A <- fastRG::dcsbm(theta, pi, B, avg_deg = 40,
                   poisson_edges = F, sort_nodes = T,
                   directed = F, allow_self_loops = F)
```

Error message: 

```
Error: Expected edge values must be not exceed 1 for bernoulli graphs. Either diminish `avg_deg` or set `poisson_edges = TRUE`.
```

**Comment by alexpghayes** [comment]
I took a look and this is catching a genuine inconsistency in the parameterization of a Bernoulli graph.

Note to self: it's probably better in the implementation to look at the maximum of `A` rather than the maximum of `B` for this check. Or I should at least convince myself these are equivalent.

**Comment by alexpghayes** [comment]
From Slack, for when I get around to looking at this more closely:

i think the implementation is correct. with those parameters (before rescaling with avg_deg) the expected degree is 20. to get to avg degree 40 all the expect probabilities get doubled, and this sends the maximum value of the expectation of A to ~2.75, which isn't possible for bernoulli graphs
1:30
i think you have three reasonable options: (1) sample a Poisson graph, optionally truncating it, (2) decrease the avg_deg, (3) decrease the degree heterogeneity
1:31
but i think the error is catching a genuine inconsistency in a parameterization of a bernoulli graph

alex  1:45 PM
the other possibility here is that it doesn't look like the identifying assumption about theta gets enforced, so we could potentially change that. i don't recall exactly what that assumption is, maybe sum(theta) == 1? so we can consider normalizing theta in the implementation

**Comment by fchen365** [comment]
In DC-SBM, the assumption on `theta` is that `sum(theta) == 1` *WITHIN EACH BLOCK*. 

Per @alexpghayes explanation, a fix for this issue is (1) first sample poisson graph, then truncate the edges.
```{R}
# sample poisson graph
A <- fastRG::dcsbm(theta, pi, B, avg_deg = 40,
                   poisson_edges = T, sort_nodes = T,
                   directed = F, allow_self_loops = F)
sign(A) # truncate
```
