### ISSUE TITLE
Return class for symmetric binary matrices is somewhat irritating

### ISSUE THREAD

**Issue by alexpghayes** [RoheLab/fastRG#2]
We should

- [ ] standardize what type of matrix you get when
- [ ] prominently document this information
- [ ] write tests to ensure we do what we say we're doing

```r
library(fastRG)
#> Loading required package: Matrix

# degree corrected stochastic block model with heterogenous nodes

n <- 1000
k <- 5

B <- matrix(0.2, nrow = k, ncol = k)  # mixing probabilities
diag(B) <- rep(0.8, k)

theta <- round(rlnorm(n, 2))  # degree parameter
pi <- 1:5 / sum(1:5)          # community membership

A <- dcsbm(theta, pi, B, avgDeg = 30, PoissonEdges = FALSE, directed = FALSE)
class(A)
#> [1] "nsCMatrix"
#> attr(,"package")
#> [1] "Matrix"
```

**Comment by alexpghayes** [comment]
The reason this is irritating is that `RSpectra::eigs_sym()` doesn't support matrices of this class, which means you need to coerce before doing an eigendecomposition. Probably worth opening an issue in `RSpectra` since this is a reasonable request.

**Comment by fchen365** [comment]
Making a request to `RSpectra` is clearly more reasonable. I agree. Outputting adjacency matrix in regular `matrix` class does not seem right, especially for sparse graphs. 

Note also that, `irlba` supports `Matrix`, which I normally would use.

**Comment by karlrohe** [comment]
I feel like I have used Rspectra with sparse matrices…  maybe I was passing it a function to perform the matrix-vector multiplication?  I’ve corresponded with the package owner before and he was very helpful.



On Aug 8, 2019, at 8:59 PM, Fan Chen <notifications@github.com<mailto:notifications@github.com>> wrote:


Making a request to RSpectra is clearly more reasonable. I agree. Outputting adjacency matrix in regular matrix class does not seem right, especially for sparse graphs.

Note also that, irlba supports Matrix, which I normally would use.

**Comment by alexpghayes** [comment]
There are various types of sparse matrices. `RSpectra` supports the major sparse matrix types, but not all sparse matrix types.

**Comment by karlrohe** [comment]
It is probably worth considering this for a bit.  Matrices in "triplet form” are super convenient for data entry type stuff. However, they are slow for everything else (i.e. all linear algebra computations).  My pattern is to load in triplet, then convert to column compressed or row compressed form.  for svd, it doesn’t matter.  For eigen, one is likely faster than the other.  easy to check.  The conversion is really fast and only needs to be done once.  can always convert back to triplet later.
kr





On Aug 9, 2019, at 10:21 AM, alex hayes <notifications@github.com<mailto:notifications@github.com>> wrote:


There are various types of sparse matrices. RSpectra supports the major sparse matrix types, but not all sparse matrix types.

**Comment by alexpghayes** [comment]
There are three components of a `Matrix` class:

- The type of data in the `Matrix` (binary, integer, double)
- Whether or not the `Matrix` is symmetric
- The storage format of the matrix (triplet versus row compressed vs column compressed)

Most extensions to the `Matrix` package support the column compressed format, and I think we should return column compressed objects in general. The issue here is not with the storage format, but the data type: in the example above we return a binary, symmetric, column-compressed Matrix object. The binary data type is not supported by `RSpectra` , which was the primary reason I opened this issue.

**Comment by karlrohe** [comment]
I see!  binary!  yes.  What I do is add 0 to the matrix M = M + 0.  probably faster ways.  you are right… RSpectra should support it.





On Aug 12, 2019, at 2:34 PM, alex hayes <notifications@github.com<mailto:notifications@github.com>> wrote:


There are three components of a Matrix class:

  *   The type of data in the Matrix (binary, integer, double)
  *   Whether or not the Matrix is symmetric
  *   The storage format of the matrix (triplet versus row compressed vs column compressed)

Most extensions to the Matrix package support the column compressed format, and I think we should return column compressed objects in general. The issue here is not with the storage format, but the data type: in the example above we return a binary, symmetric, column-compressed Matrix object. The binary data type is not supported by RSpectra , which was the primary reason I opened this issue.

**Comment by alexpghayes** [comment]
Upcoming. See `s3` branch
