### ISSUE TITLE
Output format/option for SBM and DC-SMB

### ISSUE THREAD

**Issue by fchen365** [RoheLab/fastRG#9]
For single (non-mixed) membership model, shall we consider output the membership in vector, instead of a matrix.

**Comment by alexpghayes** [comment]
If you look at the current versions of the function there are sampling functions (`dcsbm()`) and parameter calculation functions (`dcsbm_params()`). If might make sense to return a vector / matrix of community memberships from the `*_sbm_params()` function.

**Comment by fchen365** [comment]
Okay, but this prohibits `dcsbm` from generating blocks of random sizes. 
Originally, for each network, we sample the observed block sizes from a multinomial distribution (with parameter `pi`).

**Comment by alexpghayes** [comment]
I followed up in Slack but respond here as well just to close the loop on the issue.

> Okay, but this prohibits dcsbm from generating blocks of random sizes.

This doesn't, it just separates out the sampling of the latent factors from sampling the entire graph. This allows for easier inspection of the latent factors but allows exactly the same sampling that was previously available.
